---
- name: restart softether-vpnclient
  systemd:
    name: softether-vpnclient
    state: restarted

- name: restart network
  shell: "ifdown vpn_{{item.name}}; ifup vpn_{{item.name}}"
  ignore_errors: true
  loop: "{{ vpn_accounts }}"